import type { Metadata } from "next";
import { createMetadata } from "@/lib/seo/metadata";
import { HeroInner } from "@/components/sections";
import { Container, Section, Heading, Text } from "@/components/ui";

export const metadata: Metadata = createMetadata({
  title: "Terms of Service",
  description: "Read the terms and conditions governing your use of Kumusha Asset Managers services.",
  path: "/legal/terms",
});

export default function TermsOfServicePage() {
  return (
    <>
      <HeroInner
        title="Terms of Service"
        description="Last updated: January 2026"
        background="muted"
      />

      <Section background="white">
        <Container>
          <div className="max-w-3xl mx-auto prose prose-lg">
            <Heading level={2} className="text-cod-gray mb-4">
              Agreement to Terms
            </Heading>
            <Text className="text-tundora mb-6">
              By accessing or using the services of Kumusha Asset Managers, you agree 
              to be bound by these Terms of Service. If you disagree with any part of 
              these terms, you may not access our services.
            </Text>

            <Heading level={2} className="text-cod-gray mb-4 mt-8">
              Services Description
            </Heading>
            <Text className="text-tundora mb-6">
              Kumusha Asset Managers provides asset management services including but 
              not limited to vehicle management, property management, farm management, 
              and business management. The specific services, fees, and terms will be 
              outlined in individual service agreements.
            </Text>

            <Heading level={2} className="text-cod-gray mb-4 mt-8">
              Asset Owner Responsibilities
            </Heading>
            <Text className="text-tundora mb-4">
              As an asset owner, you agree to:
            </Text>
            <ul className="list-disc pl-6 text-tundora space-y-2 mb-6">
              <li>Provide accurate and complete information about your assets</li>
              <li>Ensure you have legal ownership or authority over the assets</li>
              <li>Maintain proper documentation and registration of assets</li>
              <li>Comply with all applicable laws and regulations</li>
              <li>Pay agreed-upon fees and commissions in a timely manner</li>
            </ul>

            <Heading level={2} className="text-cod-gray mb-4 mt-8">
              Our Responsibilities
            </Heading>
            <Text className="text-tundora mb-4">
              Kumusha Asset Managers commits to:
            </Text>
            <ul className="list-disc pl-6 text-tundora space-y-2 mb-6">
              <li>Manage your assets with reasonable care and professionalism</li>
              <li>Provide regular and transparent reporting</li>
              <li>Disburse earnings according to agreed schedules</li>
              <li>Maintain appropriate insurance coverage where applicable</li>
              <li>Act in your best interests as an asset owner</li>
            </ul>

            <Heading level={2} className="text-cod-gray mb-4 mt-8">
              Fees and Payment
            </Heading>
            <Text className="text-tundora mb-6">
              Our fee structure is based on a profit-sharing model as specified in 
              individual service agreements. We do not charge upfront fees. All fees 
              are deducted from revenue generated by your assets before disbursement.
            </Text>

            <Heading level={2} className="text-cod-gray mb-4 mt-8">
              Limitation of Liability
            </Heading>
            <Text className="text-tundora mb-6">
              Kumusha Asset Managers shall not be liable for any indirect, incidental, 
              special, consequential, or punitive damages resulting from your use of 
              our services. Our total liability shall not exceed the fees paid by you 
              in the twelve months preceding any claim.
            </Text>

            <Heading level={2} className="text-cod-gray mb-4 mt-8">
              Termination
            </Heading>
            <Text className="text-tundora mb-6">
              Either party may terminate the service agreement with 30 days written 
              notice. Upon termination, we will return management of your assets and 
              settle any outstanding payments within the agreed timeframe.
            </Text>

            <Heading level={2} className="text-cod-gray mb-4 mt-8">
              Governing Law
            </Heading>
            <Text className="text-tundora mb-6">
              These terms shall be governed by and construed in accordance with the 
              laws of Zimbabwe. Any disputes arising from these terms shall be resolved 
              through arbitration in Harare, Zimbabwe.
            </Text>

            <Heading level={2} className="text-cod-gray mb-4 mt-8">
              Contact
            </Heading>
            <Text className="text-tundora mb-6">
              For questions about these Terms of Service, please contact us at{" "}
              <a href="mailto:legal@kumusha.co.zw" className="text-thunderbird hover:underline">
                legal@kumusha.co.zw
              </a>
              .
            </Text>
          </div>
        </Container>
      </Section>
    </>
  );
}
